version: '3'
services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile-kafka
    ports:
      - "9092:9092"
    command: "/kafka/setup.sh"
  testrunner:
    build:
      context: .
      dockerfile: Dockerfile-testrunner
    command: "/kqm/test.sh ${BRANCH}"
  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
